name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  release:
    runs-on: windows-latest
    steps:
    - id: createBranch
      run: |
        git config --local user.email "azfuncgh@github.com"
        git config --local user.name "Azure Functions"
        git clone https://github.com/TsuyoshiUshio/GitHubActionSpike.git
        git checkout -b sub origin/sub
        git merge main
        git tag ${{ github.event.inputs.version }}
        git push
        git push ${{ github.event.inputs.version }}
    - name: Release Drafter
      uses: release-drafter/release-drafter@v5.15.0
      with:
        tag: ${{ github.event.inputs.version }}

